"""Per-table copy functions from a SQLite source into a SQLite target."""

import json
import sqlite3
from collections.abc import Mapping

from app.cli.migrate_uuid.records import MigrationStats
from app.cli.migrate_uuid.references import rewrite_metadata_references
from app.cli.migrate_uuid.sqlite_source import table_has_column
from app.cli.migrate_uuid.target_rows import SELECT_DISTINCT_TAGS_SQL
from app.cli.migrate_uuid.target_rows import access_backfill_values


def copy_context_entries(
    source: sqlite3.Connection,
    target: sqlite3.Connection,
    id_mapping: Mapping[int, str],
    stats: MigrationStats,
    dry_run: bool,
) -> None:
    """Copy every row from source ``context_entries`` to target.

    Each source row's integer ID is replaced with the corresponding
    UUIDv7 hex from ``id_mapping``. ``text_content`` and ``summary`` are
    copied verbatim. ``metadata`` is rewritten via
    :func:`rewrite_metadata_references`.

    Args:
        source: Read-only connection to the source database.
        target: Read-write connection to the target database.
        id_mapping: Integer-to-UUIDv7 mapping.
        stats: Mutated to record ``rows_migrated``.
        dry_run: When True, no INSERT is executed.
    """
    has_summary = table_has_column(source, 'context_entries', 'summary')
    has_content_hash = table_has_column(source, 'context_entries', 'content_hash')
    columns = [
        'id',
        'thread_id',
        'source',
        'content_type',
        'text_content',
        'metadata',
        'created_at',
        'updated_at',
    ]
    if has_summary:
        columns.insert(6, 'summary')
    if has_content_hash:
        columns.append('content_hash')
    select_sql = f'SELECT {", ".join(columns)} FROM context_entries ORDER BY created_at ASC, id ASC'

    cursor = source.execute(select_sql)
    insert_sql = (
        'INSERT INTO context_entries '
        '(id, thread_id, source, content_type, text_content, metadata, summary, content_hash, '
        'owner_id, visibility, created_at, updated_at) '
        'VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)'
    )
    owner_id_backfill, visibility_backfill = access_backfill_values()
    inserted = 0
    for row in cursor:
        source_id = int(row['id'])
        new_id = id_mapping[source_id]
        rewritten_metadata = rewrite_metadata_references(row['metadata'], id_mapping, stats, source_id)
        summary_value = row['summary'] if has_summary else None
        content_hash_value = row['content_hash'] if has_content_hash else None
        params = (
            new_id,
            row['thread_id'],
            row['source'],
            row['content_type'],
            row['text_content'],
            rewritten_metadata,
            summary_value,
            content_hash_value,
            owner_id_backfill,
            visibility_backfill,
            row['created_at'],
            row['updated_at'],
        )
        if not dry_run:
            target.execute(insert_sql, params)
        inserted += 1
    stats.rows_migrated = inserted


def copy_tags(
    source: sqlite3.Connection,
    target: sqlite3.Connection,
    id_mapping: Mapping[int, str],
    stats: MigrationStats,
    dry_run: bool,
) -> None:
    """Copy ``tags`` rows from source to target, remapping
    ``context_entry_id``.

    The local ``tags.id`` AUTOINCREMENT counter is regenerated by the
    target schema; the original integer value is not preserved.
    """
    cursor = source.execute(SELECT_DISTINCT_TAGS_SQL)
    insert_sql = 'INSERT INTO tags (context_entry_id, tag) VALUES (?, ?)'
    inserted = 0
    for row in cursor:
        source_id = int(row['context_entry_id'])
        mapped: str | None = id_mapping.get(source_id)
        if mapped is None:
            stats.warnings.append(
                f'tags row references missing context_entry_id={source_id}; skipped',
            )
            continue
        if not dry_run:
            target.execute(insert_sql, (mapped, row['tag']))
        inserted += 1
    stats.tags_migrated = inserted


def _malformed_image_metadata_reason(value: object) -> str | None:
    """Return why an ``image_metadata`` value is undecodable, else None.

    Args:
        value: The ``image_attachments.image_metadata`` value read from the source.

    Returns:
        A reason string when the value is neither absent nor valid JSON, else None.
    """
    if value is None:
        return None
    if not isinstance(value, str):
        return f'value is a {type(value).__name__}, not the JSON text the column stores'
    try:
        json.loads(value)
    except (json.JSONDecodeError, ValueError) as exc:
        return (
            f'value is not valid JSON, so no reader can decode it: {exc}. '
            f'Correct it in the source database and rerun to migrate this attachment.'
        )
    return None


def copy_image_attachments(
    source: sqlite3.Connection,
    target: sqlite3.Connection,
    id_mapping: Mapping[int, str],
    stats: MigrationStats,
    dry_run: bool,
) -> None:
    """Copy ``image_attachments`` rows from source to target.

    The local ``image_attachments.id`` AUTOINCREMENT counter is regenerated by the
    target schema. Image payload columns are copied verbatim.

    ``image_metadata`` is the exception: it is validated as JSON before the bind. On a
    PostgreSQL target the ``$4::jsonb`` cast validates it for free and a malformed
    value is skipped with a reason; a SQLite target binds through a plain ``?`` and
    would import a payload no reader can decode. Readers degrade gracefully on such a
    row, but the migration has no business creating one, and the two targets should
    reject the same input.
    """
    cursor = source.execute(
        'SELECT context_entry_id, image_data, mime_type, image_metadata, position, created_at '
        'FROM image_attachments ORDER BY id ASC',
    )
    insert_sql = (
        'INSERT INTO image_attachments '
        '(context_entry_id, image_data, mime_type, image_metadata, position, created_at) '
        'VALUES (?, ?, ?, ?, ?, ?)'
    )
    inserted = 0
    for row in cursor:
        source_id = int(row['context_entry_id'])
        mapped: str | None = id_mapping.get(source_id)
        if mapped is None:
            stats.warnings.append(
                f'image_attachments row references missing context_entry_id={source_id}; skipped',
            )
            continue
        metadata_reason = _malformed_image_metadata_reason(row['image_metadata'])
        if metadata_reason is not None:
            stats.errors.append(
                f'image_attachments row context_entry_id={source_id} column '
                f"'image_metadata' skipped: {metadata_reason}",
            )
            continue
        if not dry_run:
            target.execute(
                insert_sql,
                (
                    mapped,
                    row['image_data'],
                    row['mime_type'],
                    row['image_metadata'],
                    row['position'],
                    row['created_at'],
                ),
            )
        inserted += 1
    stats.images_migrated = inserted


def copy_embedding_metadata(
    source: sqlite3.Connection,
    target: sqlite3.Connection,
    id_mapping: Mapping[int, str],
    stats: MigrationStats,
    dry_run: bool,
) -> None:
    """Copy ``embedding_metadata`` rows from source to target."""
    has_chunk_count = table_has_column(source, 'embedding_metadata', 'chunk_count')
    columns = ['context_id', 'model_name', 'dimensions', 'created_at', 'updated_at']
    if has_chunk_count:
        columns.append('chunk_count')
    cursor = source.execute(f'SELECT {", ".join(columns)} FROM embedding_metadata')

    target_has_chunk_count = table_has_column(target, 'embedding_metadata', 'chunk_count')
    target_columns = ['context_id', 'model_name', 'dimensions', 'created_at', 'updated_at']
    if target_has_chunk_count:
        target_columns.append('chunk_count')
    placeholders = ', '.join('?' * len(target_columns))
    insert_sql = f'INSERT INTO embedding_metadata ({", ".join(target_columns)}) VALUES ({placeholders})'

    inserted = 0
    for row in cursor:
        source_id = int(row['context_id'])
        mapped: str | None = id_mapping.get(source_id)
        if mapped is None:
            stats.warnings.append(
                f'embedding_metadata row references missing context_id={source_id}; skipped',
            )
            continue
        params: list[object] = [
            mapped,
            row['model_name'],
            row['dimensions'],
            row['created_at'],
            row['updated_at'],
        ]
        if target_has_chunk_count:
            params.append(row['chunk_count'] if has_chunk_count else 1)
        if not dry_run:
            target.execute(insert_sql, params)
        inserted += 1
    stats.embedding_metadata_migrated = inserted


def copy_embedding_chunks(
    source: sqlite3.Connection,
    target: sqlite3.Connection,
    id_mapping: Mapping[int, str],
    stats: MigrationStats,
    dry_run: bool,
) -> None:
    """Copy ``embedding_chunks`` rows from source to target.

    ``id`` (INTEGER) and ``vec_rowid`` (INTEGER) are preserved verbatim;
    only ``context_id`` is remapped.
    """
    # Probe both sides for the start_index/end_index boundary columns, mirroring
    # copy_embedding_metadata's chunk_count guard. A pre-f36266c source schema
    # (embedding_chunks created before the boundary columns and never upgraded
    # in-place by a live server -- the CLI's "run on a backup" workflow bypasses
    # that backfill) lacks them; naming them unconditionally would raise
    # sqlite3.OperationalError and abort the whole migration. When the source
    # lacks them, default to 0 (the chunking migration's own backfill default).
    source_has_boundaries = table_has_column(source, 'embedding_chunks', 'start_index')
    target_has_boundaries = table_has_column(target, 'embedding_chunks', 'start_index')

    source_columns = ['id', 'context_id', 'vec_rowid']
    if source_has_boundaries:
        source_columns += ['start_index', 'end_index']
    source_columns.append('created_at')
    cursor = source.execute(
        f'SELECT {", ".join(source_columns)} FROM embedding_chunks ORDER BY id ASC',
    )

    target_columns = ['id', 'context_id', 'vec_rowid']
    if target_has_boundaries:
        target_columns += ['start_index', 'end_index']
    target_columns.append('created_at')
    placeholders = ', '.join('?' * len(target_columns))
    insert_sql = f'INSERT INTO embedding_chunks ({", ".join(target_columns)}) VALUES ({placeholders})'

    inserted = 0
    for row in cursor:
        source_id = int(row['context_id'])
        mapped: str | None = id_mapping.get(source_id)
        if mapped is None:
            stats.warnings.append(
                f'embedding_chunks row references missing context_id={source_id}; skipped',
            )
            continue
        params: list[object] = [row['id'], mapped, row['vec_rowid']]
        if target_has_boundaries:
            params += [
                row['start_index'] if source_has_boundaries else 0,
                row['end_index'] if source_has_boundaries else 0,
            ]
        params.append(row['created_at'])
        if not dry_run:
            target.execute(insert_sql, params)
        inserted += 1
    stats.embedding_chunks_migrated = inserted


def copy_vec_embeddings_sqlite(
    source: sqlite3.Connection,
    target: sqlite3.Connection,
    stats: MigrationStats,
    dry_run: bool,
) -> None:
    """Copy ``vec_context_embeddings`` rows from source to target.

    Both ``rowid`` and the ``embedding`` BLOB are copied verbatim. The
    bridge from public TEXT ``context_id`` to INTEGER ``rowid`` lives in
    ``embedding_chunks.vec_rowid``; the vec0 table itself has no
    ``context_id`` column.

    Requires the sqlite-vec extension to be loaded on both connections.
    """
    cursor = source.execute('SELECT rowid, embedding FROM vec_context_embeddings ORDER BY rowid ASC')
    insert_sql = 'INSERT INTO vec_context_embeddings(rowid, embedding) VALUES (?, ?)'
    inserted = 0
    for row in cursor:
        if not dry_run:
            target.execute(insert_sql, (row['rowid'], row['embedding']))
        inserted += 1
    stats.vec_rows_migrated = inserted
